#-----------------------------------------------------
# CI workflow for linting the VibroSonics web
# application
#-----------------------------------------------------

name: ESLint Web App

defaults:
  run:
    working-directory: ./WebApp

on:
  push:
    paths:
      - ".github/workflows/*.yaml"
    branches: 
        - main
        - 25-26_dev
  pull_request:
    paths:
      - ".github/workflows/*.yaml"
    branches:
        - main
        - 25-26_dev

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

        # For faster workflows
      - name: Setup Node.js and caching
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm install
      
      - name: Run ESLint
        run: npm run lint
